import type { User } from "@/types"

export const users: User[] = [
  {
    id: "1",
    name: "Jane Cooper",
    email: "jane.cooper@example.com",
    phone: 5551234001,
    emergency_phone: null,
    home_address: "742 Evergreen Terrace",
    accepted_terms: true,
    subcription: "pro",
    profile_picture: "https://i.pravatar.cc/150?img=47",
    created_at: "2025-11-02T09:12:34Z",
    is_safe: true,
    is_agent: false,
    deviceIds: ["dev-1"],
  },
  {
    id: "2",
    name: "John Doe",
    email: "john.doe@example.com",
    phone: 5551234002,
    emergency_phone: 5550000002,
    home_address: "12 Main St",
    accepted_terms: true,
    subcription: "free",
    profile_picture: "https://i.pravatar.cc/150?img=12",
    created_at: "2025-10-15T14:22:00Z",
    is_safe: false,
    is_agent: true,
    deviceIds: null,
  },
  {
    id: "3",
    name: "Alex Hunt",
    email: "alex.hunt@example.com",
    phone: 5551234003,
    emergency_phone: null,
    home_address: "55 Oak Avenue",
    accepted_terms: false,
    subcription: "enterprise",
    profile_picture: null,
    created_at: "2025-09-01T08:00:00Z",
    is_safe: null,
    is_agent: false,
    deviceIds: [],
  },
  {
    id: "4",
    name: "Maya Patel",
    email: "maya.patel@example.com",
    phone: 5551234004,
    emergency_phone: 5559990004,
    home_address: "8 Birch Lane",
    accepted_terms: true,
    subcription: "pro",
    profile_picture: "https://i.pravatar.cc/150?img=65",
    created_at: "2025-08-21T11:30:00Z",
    is_safe: true,
    is_agent: false,
    deviceIds: ["dev-7", "dev-8"],
  },
  {
    id: "5",
    name: "Carlos Gomez",
    email: "carlos.gomez@example.com",
    phone: 5551234005,
    emergency_phone: null,
    home_address: "24 Pine Road",
    accepted_terms: true,
    subcription: "free",
    profile_picture: "https://i.pravatar.cc/150?img=3",
    created_at: "2025-07-11T17:05:00Z",
    is_safe: false,
    is_agent: true,
    deviceIds: ["dev-2"],
  },
  {
    id: "6",
    name: "Sofia Rossi",
    email: "sofia.rossi@example.com",
    phone: 5551234006,
    emergency_phone: null,
    home_address: "101 Maple Street",
    accepted_terms: true,
    subcription: "pro",
    profile_picture: "https://i.pravatar.cc/150?img=30",
    created_at: "2025-06-30T07:45:00Z",
    is_safe: true,
    is_agent: false,
    deviceIds: ["dev-9"],
  },
  {
    id: "7",
    name: "Liam Nguyen",
    email: "liam.nguyen@example.com",
    phone: 5551234007,
    emergency_phone: null,
    home_address: "200 Cedar Blvd",
    accepted_terms: false,
    subcription: "free",
    profile_picture: "https://i.pravatar.cc/150?img=88",
    created_at: "2025-05-20T10:10:00Z",
    is_safe: null,
    is_agent: false,
    deviceIds: null,
  },
  {
    id: "8",
    name: "Asha Singh",
    email: "asha.singh@example.com",
    phone: 5551234008,
    emergency_phone: 5553214321,
    home_address: "9 Cherry Lane",
    accepted_terms: true,
    subcription: "enterprise",
    profile_picture: "https://i.pravatar.cc/150?img=27",
    created_at: "2025-04-12T13:20:00Z",
    is_safe: true,
    is_agent: true,
    deviceIds: ["dev-11"],
  },
  {
    id: "9",
    name: "Noah Davis",
    email: "noah.davis@example.com",
    phone: 5551234009,
    emergency_phone: null,
    home_address: "77 Willow Drive",
    accepted_terms: true,
    subcription: "pro",
    profile_picture: null,
    created_at: "2025-03-04T09:00:00Z",
    is_safe: false,
    is_agent: false,
    deviceIds: [],
  },
  {
    id: "10",
    name: "Olivia Brown",
    email: "olivia.brown@example.com",
    phone: 5551234010,
    emergency_phone: null,
    home_address: "3 River Road",
    accepted_terms: true,
    subcription: "pro",
    profile_picture: "https://i.pravatar.cc/150?img=56",
    created_at: "2025-01-15T12:00:00Z",
    is_safe: true,
    is_agent: false,
    deviceIds: ["dev-10"],
  },
]
